services:
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: "on-failure"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    build:
      context: mariadb/
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: "on-failure"
    ports:
      - "3306"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: wordpress/
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: "on-failure"
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  adminer:
    build:
      context: adminer/
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    restart: "on-failure"
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
