services:

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: "on-failure"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    build:
      context: mariadb/
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: "on-failure"
    ports:
      - "3306"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: wordpress/
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: "on-failure"
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    ports:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

#### Bonus services ####

  adminer:
    build:
      context: adminer/
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    restart: "on-failure"
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception

  cadvisor:
    build:
      context: cadvisor/
      dockerfile: Dockerfile
    container_name: cadvisor
    restart: "on-failure"
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
    ports:
      - "8081:8080"
    networks:
      - inception

  redis:
    image: redis
    build: 
      context: redis/
      dockerfile: Dockerfile
    container_name: redis
    restart: "on-failure"
    ports:
      - "6379:6379"
    networks:
      - inception

#### not ok ####

  ftp:
    build:
      context: ftp/
      dockerfile: Dockerfile
    container_name: ftp
    restart: "on-failure"
    env_file:
      - .env
    ports:
      - "20-21:20-21"
      - "21100-21110:21100-21110"
    volumes:
      -  wordpress_data:/home/user
    networks:
      - inception

  topo:
    build:
      context: topo/
      dockerfile: Dockerfile
    image: topo
    container_name: topo
    restart: "on-failure"
    ports:
      - "8082:80"
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
  minecraft_data:
