services:
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: "on-failure"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - worldpress_data:/var/www/html

  mariadb:
    build:
      context: mariadb/
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: "on-failure"
    ports:
      - "3306"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: wordpress/
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: "on-failure"
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - "9000"
    networks:
      - inception
    volumes:
      - worldpress_data:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
  worldpress_data:
