services:
  nginx:
    build:
      context: ./requirements/nginx/
    image: nginx
    container_name: nginx
    restart: "on-failure"
    ports:
      - "42443:443"

  mariadb:
    build:
      context: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: "on-failure"
    ports:
      - "13306:3306"
    env_file: "mariadb.env"