services:

  nginx:
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: "on-failure"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: "on-failure"
    ports:
      - "3306"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: "on-failure"
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    ports:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

#### Bonus services ####

  adminer:
    build:
      context: requirements/bonus/adminer/
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    restart: "on-failure"
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception

  cadvisor:
    build:
      context: requirements/bonus/cadvisor/
      dockerfile: Dockerfile
    image: cadvisor
    container_name: cadvisor
    restart: "on-failure"
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
    ports:
      - "8081:8080"
    networks:
      - inception

  redis:
    image: redis
    build: 
      context: requirements/bonus/redis/
      dockerfile: Dockerfile
    container_name: redis
    restart: "on-failure"
    ports:
      - "6379:6379"
    networks:
      - inception

  g701:
    build:
      context: requirements/bonus/g701/
      dockerfile: Dockerfile
    image: g701
    container_name: g701
    restart: "on-failure"
    ports:
      - "701:701"
    networks:
      - inception

  ftp:
    build:
      context: requirements/bonus/ftp/
      dockerfile: Dockerfile
    image: ftp
    container_name: ftp
    restart: "on-failure"
    env_file:
      - .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
  minecraft_data:
